Connectors.md
=> Fixing connector names

.travis.yml, scripts/schema_validate.js, scripts/travis_release.sh, scripts/workflow-schema.json
Schema validation of workflow.json found in PR. We use `ajv` library for validation and execute shell commands using `shelljs` library. 
Initially I tried using `simple-git` library to execute git commands and find all `workflow.json` files from PR. Locally it worked OK but on travis CI it was causing issues on remote branch. 
AJV seems popular for schema validation
https://www.npmtrends.com/ajv-vs-hapi-vs-joi-vs-json-schema-vs-jsonschema
Verified locally and on remote branch. 
https://oktainc.atlassian.net/browse/OKTA-330415
=> Vmoharir schema validation

README.md, scripts/travis_release.sh
Fixes the check for readme file location
Update README instructions to skip ci
=> fix read-me checks and update instructions to skip ci

scripts/schema_validate.js
Fix OKTA-349735. Issue was related to backticks not supported. Added a single quote to fix this issue.
=> OKTA-349735: fix env variable issue on travis ci config

.travis.yml, README.md, scripts/schema_validate.js
RCA: https://oktainc.atlassian.net/browse/OKTA-360271?focusedCommentId=1728658
=> OKTA-360271: fix Ajv error on travis-CI

workflows/contractor_expiry_notification/workflow.json, workflows/onboard_and_offboard_with_office365/workflow.json
@charleschan-okta 
I edited the descriptions for two templates. I already ran this by Arvil. Assigning the pull request to you.
=> Mark M - edits to descriptions for two newest template packs

workflows/contractor_expiry_notification/readme.md, workflows/notify_user_on_profile_update/readme.md, workflows/notify_user_on_profile_update/workflow.json, workflows/office365_create_guest_users/readme.md, workflows/office365_create_guest_users/workflow.json
@charleschan-okta 
Here's the PR for the description edits on the workflows templates repo side for the two additional templates (and I edited a third one again).
I've updated the same descriptions in both the .json and readme files if they occur in both.
=> Mark M description edits in WF repo

scripts/workflow-schema.json
OKTA-365443: add optional `details` property on schema validation
=> OKTA-365443: schema changes for optional details property

workflows/generate_unique_emails/workflow.json
Was looking at this template in my environment and noticed a typo, thought I'd submit a PR.
=> generate_unique_emails description typo

workflows/raw_http_connection_gsuite/workflow.json
Updated description and added details for raw_http_connection_gsuite requested in app-catalog-templates:
- https://github.com/okta/app-catalog-templates/pull/48
Jira Ticket:
- https://oktainc.atlassian.net/browse/OKTA-372900
=> Updated description and added details for raw_http_connection_gsuite

workflows/new_user_registration/readme.md
=> change to new_user_registration readme.md title and prerequisites

workflows/raw_http_connection_gsuite/readme.md
we don't receive refresh tokens - this would at least help to address https://github.com/okta/workflows-templates/issues/80
=> add note to limitations and known issues

workflows/send_email_with_attachment/readme.md
readme was missing, when you clicked "Setup Guide" from within Workflows it brought you to a blank page here.
=> readme was missing.

scripts/json-details-scripts/details_validator.js, useCases.json
Ticket: https://oktainc.atlassian.net/browse/OKTA-458992
- Create a new JSON file for documenting all the possible use cases
- Add validation rules for the `useCases` field on the `workflow.json` file
=> OKTA-458992: add use cases to workflows

workflows/access_request_with_slack/workflow.json, workflows/assign_temporary_group_memberships/workflow.json, workflows/contractor_expiry_notification/workflow.json, workflows/create_report_on_okta_events/workflow.json, workflows/form_submission_to_workflows_api_endpoint/workflow.json, workflows/generate_unique_emails/workflow.json, workflows/generate_unique_username/workflow.json, workflows/googledrive_file_transfer/workflow.json, workflows/identify_inactive_okta_users/workflow.json, workflows/import_users_google_sheets/workflow.json, workflows/initiate_flow_with_api_endpoint/workflow.json, workflows/intro_custom_api_actions/workflow.json, workflows/intro_to_lists_and_child_flows/workflow.json, workflows/manage_group_members_using_profile_attributes/workflow.json, workflows/onboard_and_offboard_with_office365/workflow.json, workflows/send_a_welcome_email_to_new_user_of_an_application/workflow.json, workflows/suspend_inactive_users/workflow.json, workflows/temporarily_exempt_users_from_mfa/workflow.json
Added `most-popular` and/or `introductory` tags to `details` object on some templates per https://docs.google.com/spreadsheets/d/13fAGrEfwuxGLvbk1VqcZDkgjxbm938wSS6jMWX7-ED0/edit?usp=sharing
=> OKTA-470660: Added template tag categorization

README.md
Resolves:
https://oktainc.atlassian.net/browse/OKTA-487853
=> OKTA-487853: link to the tutorial in the screenshots paragraph

workflows/manage_oncall_rotation_and_schedules_with_opsgenie/workflow.json
Fixes screenshot (resources) linking in template metadata for Manage On-Call Rotations and Schedules with Opsgenie
Resolves: OKTA-531770
=> Remaps resource images to the appropriate flow

workflows/manage_access_to_github_repo_based_on_secure_code_/workflow.json
=> Adds github connector reference to SCW template

workflows/manage_access_to_github_repo_based_on_secure_code_/workflow.json
Updates Secure Code Warrior template description for improved clarity
=> Update description text for SCW template

workflows/remotely_lock_all_kandji_devices_based_on_security/readme.md
two instances of "Kadji" replaced with "Kandji"
=> update kandji readme

workflows/generate_unique_username_with_user_import_inline_h/workflow.json
Modify template Jira ticket: https://oktainc.atlassian.net/browse/OKTA-609166
The main Jira ticket: [WT-300](https://oktainc.atlassian.net/browse/WT-300)
=> Modify Template: generate_unique_username_with_user_import_inline_h

workflows/using_okta_workflows_for_pendo_metadata_sync/workflow.json
Modify the description and link fields in workflow.json.
=> Modify Template: using_okta_workflows_for_pendo_metadata_sync

workflows/implementing_xaas_with_personio/workflow.json, workflows/implementing_xaas_with_smarthr/workflow.json
Two templates .json are revised, A screenshot mapping is corrected.
- [Implementing XaaS with Personio](https://oktainc.atlassian.net/browse/OKTA-638942)
- [Implementing XaaS with SmartHR](https://oktainc.atlassian.net/browse/OKTA-638929)
@JirongYang-okta please review the changes.
=> [OKTA-638949] fix: modify descriptions in .json

.circleci/config.yml
Link to ticket required by security: [OKTA-624783](https://oktainc.atlassian.net/browse/OKTA-624783)
=> OKTA-624783: Added required semgrep scan to workflows-templates

workflows/examples_of_openai_prompts/workflow.json
Ticket: https://oktainc.atlassian.net/browse/OKTA-682969
Main change: 
Modify one screenshot mismatch in workflow.json of Examples of OpenAI prompts.
=> [OKTA-682969] fix: correct screenshot in workflow.json

workflows/yubico_fido_preregistration/workflow.json
Jira ticket: https://oktainc.atlassian.net/browse/OKTA-791786
Description:
The screenshot attached to flow **Map FactorID to Key ID** has wrong format.
@JirongYang-okta please approve~
=> [OKTA-791786] fix: modify workflow.json for template yubico_fido_preregistration

workflows/yubico_fido_preregistration/readme.md
[OKTA-832249] fix : update setup link for yubico template
Resolves JIRA ticket:https://oktainc.atlassian.net/browse/OKTA-832249
Please review : @runzeng-okta
=> [OKTA-832249] fix : update setup link for yubico template

workflows/yubico_fido_preregistration/workflow.json
[OKTA-832249] fix : update setup link in workflows.json file for yubico template
Resolves JIRA ticket:https://oktainc.atlassian.net/browse/OKTA-832249
Please review : @runzeng-okta
=> [OKTA-832249] fix : update setup link in workflows.json file for yubico template

scripts/json-details-scripts/deleteDirec.js, scripts/json-details-scripts/details_modifier.js, scripts/json-details-scripts/image_hasher.js, scripts/json-details-scripts/readme.md, scripts/json-details-scripts/testImageUpdate.js, scripts/json-details-scripts/testfile.js, scripts/json-details-scripts/utils.js
Description: (Changes)
1. updated the scripts `details_modifier.js,image_hasher.js and utils.js `scripts to automate process of adding screenshotURL after generating hashed images.
2. Scripts now handles deleting the extra image which no longer points to any flow. Replaces the image screenshot url with the new updated screenshot in the resources folder as well as in the workflow.json
3. We can use the same `node scripts/json-details-scripts/image_hasher.js --template <your_template_folder_name>` for producing the image and adding it to json file. 
Please review:
@runzeng-okta
=> updated the scripts details_modifier.js,image_hasher.js and utils.js

workflows/identify_inactive_okta_users/workflow.json
Reference doc - https://docs.google.com/document/d/1zhaHvJi-CvtJNoXmYOpsa9WtR4hjmigLUaxZI54LqTI/edit?tab=t.0
=> Appending appropriate tags to identify_inactive_okta_users template
